### ISSUE TITLE
windows + python3.5 not work

### ISSUE THREAD

**Issue by liujshi** [neopenx/Dragon#5]
windows + python2.7 is ok
but windows + python3.5 has some problems mainly caused by Incompatibility bewteen protobuf2.6 and python3

**Comment by PhyscalX** [comment]
We have tested it on windows with python 3.6(Anaconda), it is all OK.
The python proto files generated by protoc 2.6 work compatibly with the pb3+ installed from pip.
May be update your protobuf of python? (pip install --upgrade protobuf)

And could you show the specific incompatible errors or checks?  During compiling or running?
Also, i am sure that there are no relations between pb2.6 and py3 during compiling.

**Comment by liujshi** [comment]
runing
on python35  the python kernel will crash， when save snapshots
![image](https://user-images.githubusercontent.com/4653865/29003187-92402b82-7ae4-11e7-88b9-bfac2f5a2203.png)

**Comment by liujshi** [comment]
when gen lmdb file in cifar10
the datum.SerializeToString() return bytes not str, which has no .encoded() method
![image](https://user-images.githubusercontent.com/4653865/29003258-0174f5a4-7ae6-11e7-8ad7-85b17963dc38.png)

![image](https://user-images.githubusercontent.com/4653865/29003261-0dfec142-7ae6-11e7-91aa-2b6ffdf6f43a.png)

**Comment by liujshi** [comment]
![image](https://user-images.githubusercontent.com/4653865/29003265-2203b74c-7ae6-11e7-8154-045a2291347c.png)

**Comment by PhyscalX** [comment]
Thanks, we have fixed it.
It is well known that python3 split 'str' into 'unicode' and 'bytes', which makes C APIs more confused.
In core/workspace.py, we tried to pass a 'str' to C++ backend, but parsed it still with ``PyBytes_AsString``. As in python3, ``PyUnicode_AsUTF8`` should be used instead. 

An elegant way is to use``pybind11``, which provides a safe wrapper for C++11, and it has been used in recent commits of Caffe2.  We still use naive Python APIs because it requires minimal dependencies. (Attention: ``pybind11`` support VS2015 with update2+ only)
